date=["first", "second", "third", "fourth","fifth", "sixth", "seventh", "eighth","ninth","tenth","eleventh","twelfth"]
def days (day):
    print("On the",date[day-1],"day of Christmas,\nMy true love gave to me")
    if day>11:print("Twelve drummers drumming,")
    if day>10:print("Eleven pipers piping,")
    if day>9:print("Ten lords a-leaping,")
    if day>8:print("Nine ladies dancing,")
    if day > 7: print("Eight maids a-milking,")
    if day > 6: print("Seven swans a-swimming,")
    if day > 5: print("Six geese a-laying,")
    if day > 4: print("Five golden rings,")
    if day > 3: print("Four calling birds,")
    if day > 2: print("Three French hens,")
    if day > 1 and day == 12: print("Two turtle doves,\nAnd a partridge in a pear tree!")
    if day >1 and day!= 12: print("Two turtle doves,\nAnd a partridge in a pear tree.\n")
    elif day == 1:print("A partridge in a pear tree.\n")
    
print(days(1))
print(days(2))
print(days(3))
print(days(4))
print(days(5))
print(days(6))
print(days(7))
print(days(8))
print(days(9))
print(days(10))
print(days(11))
print(days(12))